// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQoYZnn17tkjG_PM4uApXp6LaxyfX1Qd0',
    appId: '1:1068510564518:web:78eef492c9e5c78a1b2467',
    messagingSenderId: '1068510564518',
    projectId: 'pedras-chessman-projeto',
    authDomain: 'pedras-chessman-projeto.firebaseapp.com',
    databaseURL: 'https://pedras-chessman-projeto-default-rtdb.firebaseio.com',
    storageBucket: 'pedras-chessman-projeto.firebasestorage.app',
    measurementId: 'G-0D19TNW1ZG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJrieGtNLD6J5dYnTMbB9RHU1ZkH_0tQA',
    appId: '1:1068510564518:android:92ba990acb84dc8e1b2467',
    messagingSenderId: '1068510564518',
    projectId: 'pedras-chessman-projeto',
    databaseURL: 'https://pedras-chessman-projeto-default-rtdb.firebaseio.com',
    storageBucket: 'pedras-chessman-projeto.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAc3IS9EZwvBv1prv14q2HhBtnDlNA5X-U',
    appId: '1:1068510564518:ios:cffdc19fbbd96a651b2467',
    messagingSenderId: '1068510564518',
    projectId: 'pedras-chessman-projeto',
    databaseURL: 'https://pedras-chessman-projeto-default-rtdb.firebaseio.com',
    storageBucket: 'pedras-chessman-projeto.firebasestorage.app',
    iosBundleId: 'com.example.pedraschessman',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAc3IS9EZwvBv1prv14q2HhBtnDlNA5X-U',
    appId: '1:1068510564518:ios:cffdc19fbbd96a651b2467',
    messagingSenderId: '1068510564518',
    projectId: 'pedras-chessman-projeto',
    databaseURL: 'https://pedras-chessman-projeto-default-rtdb.firebaseio.com',
    storageBucket: 'pedras-chessman-projeto.firebasestorage.app',
    iosBundleId: 'com.example.pedraschessman',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQoYZnn17tkjG_PM4uApXp6LaxyfX1Qd0',
    appId: '1:1068510564518:web:d4440d0a478a2c451b2467',
    messagingSenderId: '1068510564518',
    projectId: 'pedras-chessman-projeto',
    authDomain: 'pedras-chessman-projeto.firebaseapp.com',
    databaseURL: 'https://pedras-chessman-projeto-default-rtdb.firebaseio.com',
    storageBucket: 'pedras-chessman-projeto.firebasestorage.app',
    measurementId: 'G-3DV0BCY051',
  );
}
